version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: librarydb
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-network

  tomcat:
    image: tomcat:9.0-jdk17
    container_name: library-api
    ports:
      - "8080:8080"
      - "8005:8005"
    volumes:
      - ./target/library-api.war:/usr/local/tomcat/webapps/library-api.war
    depends_on:
      - db
    networks:
      - library-network
    environment:
      - SPRING_PROFILES_ACTIVE=default

volumes:
  postgres_data:

networks:
  library-network:
    driver: bridge