spring:
  application:
    name: inventory

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: root
    password: inventory
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: never


---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

---
spring:
  config:
    activate:
      on-profile: prod